### ISSUE TITLE
Edit !chess.com output

### ISSUE THREAD

**Issue by Adard65536** [Cristian-A/en-passant-twitch#2]
Add " 's " to the end of a players username when outputting their ratings in chat. i.e. Adam65536's ratings
![Screenshot_20220723-080350_Twitch](https://user-images.githubusercontent.com/109620901/180604121-201dc098-b180-498e-b90e-99517d60c9c4.jpg)

**Comment by cristian-5** [comment]
Extend to replace `'s` with `'` when the username ends with `s` already.
Pay attention to the __saxon genitive__
https://en.wikipedia.org/wiki/English_possessive
