### ISSUE TITLE
Auto thanking command for subs and gifters

### ISSUE THREAD

**Issue by Adard65536** [Cristian-A/en-passant-twitch#3]
An automatic response from the bot tagging the user and saying "@user thank you for subbing to our channel check out our discord channel for extra sub only content" and "@user thank you for gifting <n> sub(s)! if you have received a sub from this kind twitch user then check out  our discord channel for extra sub only content" or something along those lines

**Comment by cristian-5** [comment]
due to twitch's super complicated `transport web-hook endpoint` api, https://dev.twitch.tv/docs/eventsub/manage-subscriptions this is going to be a pain to implement.

**Comment by cristian-5** [comment]
Also I think Zach wants to thank subscribers personally so this might be unnecessary

**Comment by cristian-5** [comment]
this is the same endpoint for raids and followers
