### ISSUE TITLE
the doom of the bot a.k.a. queue not working

### ISSUE THREAD

**Issue by Adard65536** [Cristian-A/en-passant-twitch#5]
Many commands in the queue system appear not to be working. !queue seems to be the most reliable out of them, others are very dodgey. and yes, im sure this is not how i am meant to fill out a github issue :)

**Comment by cristian-5** [comment]
yes very professional, I'll rewrite it from scratch so there will be no more issues.

**Comment by Adard65536** [comment]
![image](https://user-images.githubusercontent.com/109620901/196006460-b948b056-151a-42d9-a357-dd277594652e.png)
