### ISSUE TITLE
Toggle challenge command

### ISSUE THREAD

**Issue by Adard65536** [Cristian-A/en-passant-twitch#6]
A mod only command that changes the !challenge command from "Sorry Zach is not accepting challenges today" to "Please !join the queue and challenge Zach to an unrated game on chess.com" or something like that

**Comment by cristian-5** [comment]
does it need persistence? meaning: does it need to remember the setting from one stream to another?

**Comment by Adard65536** [comment]
Hmm,  if you have it as defaulted to off then we would eliminate the risk of people forgetting to turn it off again as realistically, Zach rarely does 2 consecutive streams of taking challenges

**Comment by cristian-5** [comment]
should I disable the queue by default at the start of a stream as well?

**Comment by Adard65536** [comment]
Yes

**Comment by cristian-5** [comment]
ok I just realised it would take me ages to re-implement the islive function so I will make it semi-persistent. meaning that when the bot goes down it resets the variable.

**Comment by Adard65536** [comment]
Would it not be possible to reset the variable with the twitch notification being sent?

**Comment by cristian-5** [comment]
This is the twitch bot not the discord bot...

**Comment by Adard65536** [comment]
So for clarification, does the twitch bot go down after time of inactivity? Does this mean that it resets or nah?

**Comment by cristian-5** [comment]
it resets every now and then
