### ISSUE TITLE
Checking Spotify API

### ISSUE THREAD

**Issue by Adard65536** [Cristian-A/en-passant-twitch#7]
At brief research Spotify at least had an API, whether that is a usable API etc, I cannot say. Would we be able to code a !song command and !playlist command which fetches whichever song Zach is playing at any given time? Ideally, not usable when Zach is not streaming for Zachs privacy but that's up to him

**Comment by cristian-5** [comment]
Twitch has an automated song title switcher, zach just needs to use it.
https://soundtrack.twitch.tv
https://help.twitch.tv/s/article/soundtrackwebplayeraudioconfig?language=en_US#studio
