### ISSUE TITLE
Bot syncing

### ISSUE THREAD

**Issue by Adard65536** [Cristian-A/en-passant-twitch#8]
I was under the impression that if I made a change to a command it should change on the twitch output almost instantly, on the attached screenshot you can see i edited a command and almost 10 minutes later it still has not updated. Not sure if this is a bot issue or am Adam issue.
![Screenshot_20221023-035426_Twitch](https://user-images.githubusercontent.com/109620901/197371077-c8caf87b-4d27-4f27-991b-add5f97723e4.jpg)
![Screenshot_20221023-035417_Discord](https://user-images.githubusercontent.com/109620901/197371079-5dcd18b3-0fe1-4767-b8d1-0b043cebac7a.jpg)

**Comment by Adard65536** [comment]
Not updated on command list either, I get the feeling this is an Adam issue
![Screenshot_20221023-040323_Samsung Internet](https://user-images.githubusercontent.com/109620901/197371455-3d1d5cbc-3aec-4f03-a501-bcaf9ec12d97.jpg)

**Comment by Adard65536** [comment]
Please refer to time stamps in top left corner

**Comment by Adard65536** [comment]
Has now updated
![Uploading Screenshot_20221023-042853_Twitch.jpg…]()

**Comment by cristian-5** [comment]
yes, I forgot to use `fetch` on edit, so it updates. eventually it can be forced by loading the commands' page once or twice while I fix it.

**Comment by cristian-5** [comment]
https://github.com/Cristian-A/en-passant-discord/commit/bcf2b5f27cdbbc71fadda7bca63c20ad1d4ae524
