### ISSUE TITLE
Ranking for Channel Points

### ISSUE THREAD

**Issue by Adard65536** [Cristian-A/en-passant-twitch#9]
I know it's possible as I have seen it in other chats. Essentially its a ranking for those with the most channel points in the community. When you use !rankings it should say "You are X position out of Y total chatters with a channel point total of Z"

**Comment by cristian-5** [comment]
I don't know if twitch requires full admin permission, 7 layers of security, your grandma's blessing and your soul in a jar for that. I am not kidding. My bank does not have twitch's security. It's like they're handing you life endangering information...

**Comment by cristian-5** [comment]
even better https://discuss.dev.twitch.tv/t/how-to-get-the-channel-points-of-a-special-user-using-twitch-api/31856
this says it's not allowed.
